from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import copy, os

OUT  = "/home/bao/ECE410-HW4AI/codefest/cf06/presentation/"
PPTX = OUT + "cf06_cllm_slides.pptx"

BLUE  = RGBColor(0x1f, 0x4e, 0x79)
GREEN = RGBColor(0x1a, 0x7a, 0x4a)
GRAY  = RGBColor(0x44, 0x44, 0x44)
WHITE = RGBColor(0xff, 0xff, 0xff)
LGRAY = RGBColor(0xf2, 0xf2, 0xf2)

W, H = Inches(13.33), Inches(7.5)

prs = Presentation()
prs.slide_width  = W
prs.slide_height = H

blank = prs.slide_layouts[6]

def add_slide():
    return prs.slides.add_slide(blank)

def rect(slide, x, y, w, h, fill=None, line=None):
    shape = slide.shapes.add_shape(1, Inches(x), Inches(y), Inches(w), Inches(h))
    shape.line.fill.background()
    if fill:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill
    else:
        shape.fill.background()
    if line:
        shape.line.color.rgb = line
        shape.line.width = Pt(1)
    else:
        shape.line.fill.background()
    return shape

def txbox(slide, text, x, y, w, h,
          size=20, bold=False, color=None, align=PP_ALIGN.LEFT,
          wrap=True):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color or GRAY
    return tb

def bullets(slide, items, x, y, w, h, size=16, color=None):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame
    tf.word_wrap = True
    for i, (indent, text) in enumerate(items):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.level = indent
        p.space_before = Pt(4)
        run = p.add_run()
        run.text = ("• " if indent == 0 else "  – ") + text
        run.font.size = Pt(size)
        run.font.color.rgb = color or GRAY

def img(slide, path, x, y, w=None, h=None):
    if w and h:
        slide.shapes.add_picture(path, Inches(x), Inches(y), Inches(w), Inches(h))
    elif w:
        slide.shapes.add_picture(path, Inches(x), Inches(y), width=Inches(w))
    else:
        slide.shapes.add_picture(path, Inches(x), Inches(y), height=Inches(h))

def header(slide, title):
    rect(slide, 0, 0, 13.33, 1.1, fill=BLUE)
    txbox(slide, title, 0.3, 0.1, 12.7, 0.9,
          size=32, bold=True, color=WHITE)
    rect(slide, 0, 1.1, 13.33, 0.06, fill=GREEN)

# ── SLIDE 1: TITLE ────────────────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=BLUE)
rect(sl, 0, 3.0, 13.33, 0.08, fill=GREEN)
txbox(sl, "Codefest 6 — CLLM", 0.5, 1.2, 12.3, 1.4,
      size=52, bold=True, color=WHITE, align=PP_ALIGN.CENTER)
txbox(sl, "4×4 Binary-Weight Crossbar MAC", 0.5, 2.8, 12.3, 0.8,
      size=28, color=RGBColor(0xbf, 0xd7, 0xed), align=PP_ALIGN.CENTER)
txbox(sl, "Generated by Claude Sonnet 4.6  ·  ECE 410/510 Spring 2026  ·  Bao Nguyen",
      0.5, 6.4, 12.3, 0.7,
      size=16, color=RGBColor(0x9d, 0xc3, 0xe6), align=PP_ALIGN.CENTER)

# ── SLIDE 2: WHAT THE CROSSBAR DOES ──────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "What Is a Crossbar MAC?")

img(sl, OUT + "crossbar.png", 0.3, 1.3, h=5.5)

bullets(sl, [
    (0, "Four 8-bit signed inputs (rows)"),
    (0, "4×4 weight matrix — each weight is +1 or −1"),
    (0, "Four 10-bit signed outputs (columns)"),
    (0, "Each output computes a dot product every cycle"),
    (0, "Grid of wires — weights sit at the intersections"),
    (0, "so basically you multiply each input by its weight"),
    (1, "at that row-column intersection and add them up"),
], 6.0, 1.5, 7.0, 5.5, size=17)

# ── SLIDE 3: MODULE ARCHITECTURE ─────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Module Architecture — 3 Stages")

img(sl, OUT + "pipeline.png", 0.3, 1.4, w=12.5)

bullets(sl, [
    (0, "Stage 1 — Weight Register"),
    (1, "flip-flop that latches full 4×4 matrix on weight_load"),
    (0, "Stage 2 — Combinational MAC"),
    (1, "just wires, no clock — computes all 4 dot products at the same time"),
    (0, "Stage 3 — Output Register"),
    (1, "latches results on next rising edge"),
], 0.4, 4.4, 12.5, 2.9, size=16)

# ── SLIDE 4: WEIGHT ENCODING ──────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Weight Encoding — Flat 16-bit Register")

img(sl, OUT + "encoding.png", 0.3, 1.3, w=12.5)

bullets(sl, [
    (0, "bit (4i + j) holds weight[i][j]"),
    (1, "For an example: bit 0 = w[0][0],  bit 4 = w[1][0]"),
    (0, "Loads the entire 4×4 matrix in exactly 1 clock cycle"),
    (0, "vs. row-by-row: 4 cycles + an address counter on top of that"),
    (0, "Claude went with flat register to keep it simple"),
], 0.4, 4.1, 12.5, 2.9, size=17)

# ── SLIDE 5: OUTPUT BIT WIDTH ─────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Output Bit Width — Why 10 Bits?")

txbox(sl, "Worst case:", 1.0, 1.5, 5.0, 0.5, size=18, bold=True, color=BLUE)

steps = [
    ("4 inputs × max value", "4 × 127  =  508"),
    ("10-bit signed range",  "−512  to  +511"),
    ("511 > 508",            "clears the threshold we need ✓"),
]
for i, (label, val) in enumerate(steps):
    y = 2.1 + i * 1.15
    rect(sl, 0.8, y, 5.5, 0.9, fill=WHITE, line=BLUE)
    txbox(sl, label, 0.9, y + 0.08, 5.3, 0.4, size=14, color=GRAY)
    txbox(sl, val,   0.9, y + 0.42, 5.3, 0.45, size=18, bold=True, color=BLUE)

    if i < 2:
        txbox(sl, "↓", 3.5, y + 0.95, 0.5, 0.3, size=16, color=GREEN, align=PP_ALIGN.CENTER)

rect(sl, 7.0, 1.5, 5.8, 4.8, fill=WHITE, line=GREEN)
txbox(sl, "Why not 9-bit?", 7.1, 1.6, 5.6, 0.5, size=15, bold=True, color=GREEN)
bullets(sl, [
    (0, "9-bit signed only goes to 255 — overflows"),
    (0, "10-bit is the minimum that covers 508"),
    (0, "No wasted bits, no overflow"),
], 7.1, 2.2, 5.5, 2.5, size=15, color=GRAY)

# ── SLIDE 6: TESTBENCH ────────────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Testbench — Setup & Hand Calculation")

txbox(sl, "Weight Matrix (from spec)", 0.4, 1.3, 5.5, 0.45,
      size=15, bold=True, color=BLUE)

wm = [
    ["+1", "−1", "+1", "−1"],
    ["+1", "+1", "−1", "−1"],
    ["−1", "+1", "+1", "−1"],
    ["−1", "−1", "−1", "+1"],
]
cell_w, cell_h = 0.9, 0.55
for r in range(4):
    for c in range(4):
        cx = 0.5 + c * cell_w
        cy = 1.8 + r * cell_h
        fc = RGBColor(0xe2, 0xef, 0xda) if wm[r][c] == "+1" else RGBColor(0xff, 0xe0, 0xe0)
        rect(sl, cx, cy, cell_w - 0.05, cell_h - 0.05, fill=fc, line=BLUE)
        txbox(sl, wm[r][c], cx, cy + 0.08, cell_w - 0.05, cell_h - 0.1,
              size=14, bold=True,
              color=GREEN if wm[r][c] == "+1" else RGBColor(0xc0, 0x00, 0x00),
              align=PP_ALIGN.CENTER)

txbox(sl, "Inputs: x = [10, 20, 30, 40]", 0.4, 4.2, 5.5, 0.5,
      size=15, bold=True, color=BLUE)

txbox(sl, "Hand-calculated expected outputs", 6.2, 1.3, 6.8, 0.45,
      size=15, bold=True, color=BLUE)

calcs = [
    ("y[0]", "+10 + 20 − 30 − 40", "= −40"),
    ("y[1]", "−10 + 20 + 30 − 40", "=    0"),
    ("y[2]", "+10 − 20 + 30 + 40", "= −20"),  # wait let me recalc
    ("y[3]", "−10 − 20 − 30 + 40", "= −20"),  # wait let me recalc
]
# Let me recalculate:
# weight matrix is:
# row 0: +1 -1 +1 -1  -> y[col] gets w[row][col] * x[row]
# Actually: y[col] = sum over rows of w[row][col] * x[row]
# col 0: w[0][0]*x[0] + w[1][0]*x[1] + w[2][0]*x[2] + w[3][0]*x[3]
#       = +1*10 + +1*20 + +1*30 + +1*40 = 100? wait that doesn't match
#
# Wait, the script says:
# "column zero — you get plus-ten from row 0, plus-twenty from row 1,
#  and then minus-thirty and minus-forty from rows 2 and 3"
# So col 0: +10 + 20 - 30 - 40 = -40
# That means weights for col 0 are: +1, +1, -1, -1 (from rows 0,1,2,3)
#
# But from the weight matrix as shown:
# row 0: [+1, -1, +1, -1]
# row 1: [+1, +1, -1, -1]
# row 2: [+1, -1, -1, +1]
# row 3: [+1, +1, +1, +1]
#
# col 0: w[0][0]=+1, w[1][0]=+1, w[2][0]=+1, w[3][0]=+1
# So col 0 = +10 + 20 + 30 + 40 = 100? That doesn't match -40 either.
#
# Wait, I need to reconsider the weight matrix layout.
# The testbench script says:
# "plus-one, minus-one, plus-one, minus-one on row zero" -> w[0] = [+1,-1,+1,-1]
# The calculation says col 0 = +10 + 20 - 30 - 40 = -40
#
# That means for col 0: w[0][0]=+1, w[1][0]=+1, w[2][0]=-1, w[3][0]=-1
#
# So the actual weight matrix must be:
# Row 0: [+1, ?, ?, ?]  w[0][0]=+1
# Row 1: [+1, ?, ?, ?]  w[1][0]=+1
# Row 2: [-1, ?, ?, ?]  w[2][0]=-1
# Row 3: [-1, ?, ?, ?]  w[3][0]=-1
#
# But the script says row 0 = "+1, -1, +1, -1"... so that's columns within row 0.
# If w[row][col] then y[col] = sum_row w[row][col] * x[row]
# y[0] = w[0][0]*10 + w[1][0]*20 + w[2][0]*30 + w[3][0]*40
#
# From the script: y[0] = +10 + 20 - 30 - 40 = -40
# So: w[0][0]=+1, w[1][0]=+1, w[2][0]=-1, w[3][0]=-1
#
# But from the weight spec "row zero: +1,-1,+1,-1"
# w[0][0]=+1, w[0][1]=-1, w[0][2]=+1, w[0][3]=-1
#
# These are inconsistent... unless the weight matrix from the cman is:
# Row 0: +1, -1, +1, -1  (this is w[0][0..3])
# Row 1: +1, +1, -1, -1  (this is w[1][0..3])
#
# And y[col] = sum_row w[row][col] * x[row]
# y[0] = w[0][0]*10 + w[1][0]*20 + w[2][0]*30 + w[3][0]*40
#      = +1*10 + +1*20 + ??? * 30 + ??? * 40
#
# From spoken script: y[0] = +10 + 20 - 30 - 40 = -40
# So w[2][0] = -1, w[3][0] = -1
#
# So row 2 starts with -1, row 3 starts with -1.
# Row 2: -1, ?, ?, ?
# Row 3: -1, ?, ?, ?
#
# But the spoken script for testbench says:
# "plus-one, minus-one, plus-one, minus-one on row zero"
# "plus-one, plus-one, minus-one, minus-one on row one"
# "and so on"
#
# The original CF06 testbench code from the HDL files should tell me exactly.
# Let me just use the correct values from the simulation log which showed -40, 0, -20, -20.
#
# Actually let me not recalculate this here. The weight_in from the testbench was:
# weight_in = {4'b1000, 4'b0110, 4'b0011, 4'b0101}
# which is bits [15:12]=1000, [11:8]=0110, [7:4]=0011, [3:0]=0101
# bit 4i+j = weight[i][j]: 1=+1, 0=-1
# w[row][col] = bit(4*row + col)
# Row 0 (bits 3:0 = 0101): w[0][0]=1,w[0][1]=0,w[0][2]=1,w[0][3]=0 → +1,-1,+1,-1 ✓
# Row 1 (bits 7:4 = 0011): w[1][0]=1,w[1][1]=1,w[1][2]=0,w[1][3]=0 → +1,+1,-1,-1 ✓
# Row 2 (bits 11:8 = 0110): w[2][0]=0,w[2][1]=1,w[2][2]=1,w[2][3]=0 → -1,+1,+1,-1
# Row 3 (bits 15:12 = 1000): w[3][0]=0,w[3][1]=0,w[3][2]=0,w[3][3]=1 → -1,-1,-1,+1
#
# Now: y[col] = sum_row w[row][col] * x[row] with x=[10,20,30,40]
# y[0] = w[0][0]*10 + w[1][0]*20 + w[2][0]*30 + w[3][0]*40
#       = +1*10 + +1*20 + -1*30 + -1*40
#       = 10 + 20 - 30 - 40 = -40 ✓
#
# y[1] = w[0][1]*10 + w[1][1]*20 + w[2][1]*30 + w[3][1]*40
#       = -1*10 + +1*20 + +1*30 + -1*40
#       = -10 + 20 + 30 - 40 = 0 ✓
#
# y[2] = w[0][2]*10 + w[1][2]*20 + w[2][2]*30 + w[3][2]*40
#       = +1*10 + -1*20 + +1*30 + -1*40
#       = 10 - 20 + 30 - 40 = -20 ✓
#
# y[3] = w[0][3]*10 + w[1][3]*20 + w[2][3]*30 + w[3][3]*40
#       = -1*10 + -1*20 + -1*30 + +1*40
#       = -10 - 20 - 30 + 40 = -20 ✓
#
# Great! So the actual weight matrix is:
# Row 0: +1, -1, +1, -1
# Row 1: +1, +1, -1, -1
# Row 2: -1, +1, +1, -1
# Row 3: -1, -1, -1, +1
#
# I had the wrong matrix in my gen_diagrams.py! Let me fix it.
# The crossbar grid and the testbench slide weight matrix both show wrong values.
# I need to fix:
# weights in gen_diagrams.py (crossbar.png)
# and the wm table in build_pptx.py (slide 6)

# OK I realize I have errors in the weight matrix. Let me fix all of this.
# The correct weight matrix is:
# Row 0: +1, -1, +1, -1
# Row 1: +1, +1, -1, -1
# Row 2: -1, +1, +1, -1
# Row 3: -1, -1, -1, +1

calcs = [
    ("y[0]", "+10 + 20 − 30 − 40", "= −40"),
    ("y[1]", "−10 + 20 + 30 − 40", "=    0"),
    ("y[2]", "+10 − 20 + 30 − 40", "= −20"),
    ("y[3]", "−10 − 20 − 30 + 40", "= −20"),
]

for i, (out, calc, result) in enumerate(calcs):
    y = 1.8 + i * 1.2
    rect(sl, 6.2, y, 6.8, 1.0, fill=WHITE, line=BLUE)
    txbox(sl, out, 6.3, y + 0.05, 0.8, 0.4, size=13, bold=True, color=BLUE)
    txbox(sl, calc, 7.1, y + 0.05, 4.0, 0.4, size=13, color=GRAY)
    txbox(sl, result, 11.2, y + 0.05, 1.7, 0.4, size=13, bold=True, color=GREEN)

# ── SLIDE 7: TIMING ───────────────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Testbench — 2-Cycle Output Latency")

img(sl, OUT + "timing.png", 0.3, 1.3, w=8.5)

bullets(sl, [
    (0, "Output shows up 2 cycles after weight_load, not 1"),
    (0, "Why:"),
    (1, "Cycle 1 rising edge → weight register latches new weights"),
    (1, "BUT output register clocks on same edge with old weights"),
    (1, "Cycle 2 rising edge → output register latches correct result"),
    (0, "Testbench waits 2 cycles before reading outputs"),
], 9.0, 1.5, 4.0, 5.5, size=15)

# ── SLIDE 8: RESULTS ──────────────────────────────────────────────────────────
sl = add_slide()
rect(sl, 0, 0, 13.33, 7.5, fill=LGRAY)
header(sl, "Simulation Results")

img(sl, OUT + "results.png", 1.0, 1.4, w=7.0)

bullets(sl, [
    (0, "All four outputs match what I expected"),
    (0, "Exactly what the hand calculation said"),
    (0, "4 out of 4 — pretty good"),
], 8.5, 2.0, 4.5, 3.0, size=18, color=BLUE)

prs.save(PPTX)
print(f"Saved {PPTX}")
print(f"Total slides: {len(prs.slides)}")
