from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

OUT  = "/home/bao/ECE410-HW4AI/codefest/cf06/presentation/"
PPTX = OUT + "cf06_cllm_slides.pptx"

BLUE  = RGBColor(0x1f, 0x4e, 0x79)
GREEN = RGBColor(0x1a, 0x7a, 0x4a)
GRAY  = RGBColor(0x22, 0x22, 0x22)
WHITE = RGBColor(0xff, 0xff, 0xff)
LGRAY = RGBColor(0xf4, 0xf4, 0xf4)

W, H = Inches(13.33), Inches(7.5)

prs = Presentation()
prs.slide_width  = W
prs.slide_height = H
blank = prs.slide_layouts[6]

def slide():
    return prs.slides.add_slide(blank)

def bg(sl, color=None):
    r = sl.shapes.add_shape(1, 0, 0, W, H)
    r.line.fill.background()
    if color:
        r.fill.solid(); r.fill.fore_color.rgb = color
    else:
        r.fill.solid(); r.fill.fore_color.rgb = LGRAY

def bar(sl):
    r = sl.shapes.add_shape(1, 0, 0, W, Inches(0.55))
    r.line.fill.background(); r.fill.solid(); r.fill.fore_color.rgb = BLUE
    r2 = sl.shapes.add_shape(1, 0, Inches(0.55), W, Inches(0.06))
    r2.line.fill.background(); r2.fill.solid(); r2.fill.fore_color.rgb = GREEN

def header(sl, text):
    bar(sl)
    tb = sl.shapes.add_textbox(Inches(0.25), Inches(0.06), Inches(13.0), Inches(0.48))
    tf = tb.text_frame; tf.word_wrap = False
    p = tf.paragraphs[0]; p.alignment = PP_ALIGN.LEFT
    r = p.add_run(); r.text = text
    r.font.size = Pt(22); r.font.bold = True; r.font.color.rgb = WHITE

def script_box(sl, lines, x, y, w, h, size=19):
    tb = sl.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tb.text_frame; tf.word_wrap = True
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.space_before = Pt(5)
        r = p.add_run(); r.text = line
        r.font.size = Pt(size); r.font.color.rgb = GRAY

def pic(sl, fname, x, y, w=None, h=None):
    kw = {}
    if w: kw['width'] = Inches(w)
    if h: kw['height'] = Inches(h)
    sl.shapes.add_picture(OUT + fname, Inches(x), Inches(y), **kw)

# ── SLIDE 1: TITLE ────────────────────────────────────────────────────────────
sl = slide()
bg(sl, BLUE)
_accent = sl.shapes.add_shape(1, 0, Inches(3.1), W, Inches(0.08))
_accent.line.fill.background(); _accent.fill.solid(); _accent.fill.fore_color.rgb = GREEN

tb = sl.shapes.add_textbox(Inches(0.5), Inches(1.1), Inches(12.3), Inches(1.6))
tf = tb.text_frame; p = tf.paragraphs[0]; p.alignment = PP_ALIGN.CENTER
r = p.add_run(); r.text = "Codefest 6 — CLLM"
r.font.size = Pt(56); r.font.bold = True; r.font.color.rgb = WHITE

tb2 = sl.shapes.add_textbox(Inches(0.5), Inches(2.85), Inches(12.3), Inches(0.7))
tf2 = tb2.text_frame; p2 = tf2.paragraphs[0]; p2.alignment = PP_ALIGN.CENTER
r2 = p2.add_run(); r2.text = "4×4 Binary-Weight Crossbar MAC"
r2.font.size = Pt(26); r2.font.color.rgb = RGBColor(0xbf, 0xd7, 0xed)

tb3 = sl.shapes.add_textbox(Inches(0.5), Inches(6.5), Inches(12.3), Inches(0.6))
tf3 = tb3.text_frame; p3 = tf3.paragraphs[0]; p3.alignment = PP_ALIGN.CENTER
r3 = p3.add_run()
r3.text = "Generated by Claude Sonnet 4.6  ·  ECE 410/510 Spring 2026  ·  Bao Nguyen"
r3.font.size = Pt(15); r3.font.color.rgb = RGBColor(0x9d, 0xc3, 0xe6)

# ── SLIDE 2: DESIGN — CROSSBAR OVERVIEW ───────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Design")

script_box(sl, [
    "For CF06 CLLM I had Claude Sonnet 4.6 generate a 4-by-4 binary-weight crossbar MAC unit in SystemVerilog.",
    "",
    "So about the design. The module takes four 8-bit signed inputs, a 4-by-4 weight matrix",
    "where each weight is either plus-one or minus-one, and produces four 10-bit signed outputs.",
    "Each clock cycle, every output computes a dot product, so basically you multiply each input",
    "by its weight at that row-column intersection and add them up. That's what the crossbar does,",
    "a grid of wires where rows carry inputs, columns carry outputs, and the weights sit at the intersections.",
], 0.3, 0.75, 7.5, 6.5)

pic(sl, "crossbar.png", 7.9, 0.8, h=6.0)

# ── SLIDE 3: DESIGN — 3 STAGES ────────────────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Design — 3 Stages")

script_box(sl, [
    "The module has three stages. First stage is the weight register, it's a flip-flop that latches",
    "the full weight matrix when you pulse weight_load high. Claude packed the entire 4-by-4 matrix",
    "into a single 16-bit flat register, where bit 4i plus j holds weight[i][j]. For an example,",
    "bit zero is weight[0][0], bit four would be weight[1][0], and so on. I asked Claude why it",
    "went with a flat register and it said it actually loads the entire matrix in exactly one clock",
    "cycle. Like if you loaded row by row, that would've taken four cycles and you'd need an address",
    "counter to track which row you're on, so the flat register just keeps it simple.",
], 0.3, 0.75, 7.5, 5.0)

pic(sl, "pipeline.png", 0.3, 5.8, w=7.5)

pic(sl, "encoding.png", 7.9, 0.75, w=5.2)

# ── SLIDE 4: DESIGN — MAC + BIT WIDTH ─────────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Design — MAC & Output Bit Width")

script_box(sl, [
    "The second stage is the combinational MAC, those are just wires, no clock, which sign-extends",
    "the inputs to 10 bits and computes all four dot products at the same time. Then the third stage",
    "is the output register, which latches the results on the next rising edge.",
    "",
    "As for the output bit width, worst case is four inputs at plus or minus 127, so 4 times 127",
    "is 508. And 10-bit signed goes up to 511, which clears the threshold we need.",
], 0.3, 0.75, 7.5, 5.5)

pic(sl, "pipeline.png", 7.9, 0.75, w=5.2)

# ── SLIDE 5: TESTBENCH — SETUP ────────────────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Testbench — Setup")

script_box(sl, [
    "So about the testbench. Claude loaded the weight matrix from the assignment spec, which is",
    "plus-one, minus-one, plus-one, minus-one on row zero, plus-one, plus-one, minus-one, minus-one",
    "on row one, and so on, and then it applied inputs of 10, 20, 30, and 40.",
    "",
    "Before running the simulation I hand-calculated the expected outputs, so for example, column zero,",
    "you get plus-ten from row 0, plus-twenty from row 1, and then minus-thirty and minus-forty from",
    "rows 2 and 3, and so that adds up to minus-40. I did the same for all four columns and got",
    "minus-40, zero, minus-20, and minus-20.",
], 0.3, 0.75, 7.5, 6.5)

pic(sl, "crossbar.png", 7.9, 0.8, h=6.0)

# ── SLIDE 6: TESTBENCH — TIMING ───────────────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Testbench — 2-Cycle Timing")

script_box(sl, [
    "One thing about the timing Claude had to get right, and the output shows up two cycles after",
    "you assert weight_load, not one. Basically here's why, so on the first rising edge after",
    "weight_load, the weight register latches the new weights, but the output register clocks on",
    "that same edge and it's still using the old weights. And so the correct output only appears",
    "one cycle later. The testbench explicitly waits two cycles before reading the outputs.",
], 0.3, 0.75, 7.5, 4.5)

pic(sl, "timing.png", 0.3, 5.2, w=7.5)
pic(sl, "pipeline.png", 7.9, 0.75, w=5.2)

# ── SLIDE 7: RESULTS ──────────────────────────────────────────────────────────
sl = slide()
bg(sl)
header(sl, "The Simulation Results")

script_box(sl, [
    "All four outputs match what I expected. Out-zero is minus-40, out-one is zero,",
    "out-two and out-three are both minus-20, exactly what my hand calculation said.",
    "So 4 out of 4, that's pretty good. Thanks.",
], 0.3, 0.75, 7.5, 3.0)

pic(sl, "results.png", 0.3, 3.8, w=7.5)
pic(sl, "crossbar.png", 7.9, 0.75, h=6.0)

prs.save(PPTX)
print(f"Saved — {len(prs.slides)} slides")
