SIM              = icarus
TOPLEVEL_LANG    = verilog
VERILOG_SOURCES  = $(PWD)/kmeans_dist_core.sv
TOPLEVEL         = kmeans_dist_core
COCOTB_TEST_MODULES = test_kmeans

include $(shell cocotb-config --makefiles)/Makefile.sim
