SIM              = icarus
TOPLEVEL_LANG    = verilog
VERILOG_SOURCES  = $(PWD)/../hdl/mac_correct.v
TOPLEVEL         = mac
MODULE           = test_mac

# Run with WAVES=1 to generate sim_build/mac.fst waveform file
# Example: make WAVES=1

include $(shell cocotb-config --makefiles)/Makefile.sim
